language: java
jdk: oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: yanisakli-github
    token:
      secure: o/x9ecVzFX/sd8W29DH5PsoI6Ct8PjXVZL3rZJajUu+HspnrvRd/6YMnZfRBJLmU5pw6XxxgTrg1H8JXydCI8ChigOQ4uaNvp7nBxx/kfXZ0+p2pFUH2jpf0YXrF0fgidExU5g0VZh5bbqsuOVSawqRVl0sneFe8nmrIRfSPvfGNlgNCAzPJK3txgd2j6BvUvLoQnbs1KhpHayICckUAl5b1/N/AGKQJwnBU3sHoECllPQhUyNTWzkc4ppnhkbjMS7gxy/M3GWeXrzcLqh3iGeDmEYyTQ/sPAKRRiPwnBJrKRjkeGNzs4EbIpuMoWzJpIwG3G8mBwSRnB8YZemWhGw8p4ye1bTdj8lV/m+YjbwffyJq9gFdQXmXyJgXZfxYGy/y04oPRcDm6P5qw4DUe23pAKvfB2s8yx59lOdL0e0ymrG8t7ELPoLh79/dnBA2aNYd7plGpjR3t5ebsgRhGb9pWGPrlyh5YBnQP3dWLpKBGLc3K3YKOVKDR8wCyL652hPu7QzRQr5B/2EX/eFNCwBH01/QKJujjexh5iRy6k7glpNfdgGcyk+KTMR72qzPzNsszNOK44hnqlnflRF/Ea3/Xv2Y6vnePHcP8pAU/2DAUTbwYmPrJZJV2LyqLGZxM2XM3yE9STpSJyxPO5lQEtp2V5vyjJLyzunkaIXZ1AdI=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yanisakli_JEE
  -DskipTests
- sonar-scanner -Dsonar.projectKey=yanisakli_JEE -Dsonar.sources=. -Dsonar.java.binaries=.

deploy:
  provider: s3
  access_key_id:
    secure: "RvxPP+8TZk3ypXhCSCT9BPJsG0Cpba94IO+ekvudoVDEnc4di0grMONRTzBtdru8g8kfyLoTAbSmtr0rNPbUBomijP+NzRWKp+ViLnOJKcX1u1mxAxEeD2JnmW2TDJd3DYnOBgbpnWboYCNXwEMghYOToz7dAzuVqMGPJiN1GLIIPGcTzVnejH3Qh6ylQFAjKzdFbW17vNWvZmpdbw80POv4qv1RtHpyrnoSJj8SzqYjxSJwczn7TtWTUaGvDKel+2c376F5FWNTjovG9to8CclJRt95VG+tGukTZoVkciqNfQYZG6T+/K3Ku0J7O5uT/vAoOSqzEtwR0b9h44NjZUmO3zr74cYUqS0MQKd7E1JbZBrqPZ9FlJrU1xmzXVxHJJNKXEN4ecqXGCTr/1x/JM4utVP5K3ii26H7lFzZ4gurjgdZVYgbfO9rNcsZTdsibeOOTXYhA5t6vEt+geVMCn6dKQWqKmWAvpuUGCmknhzRtZEpoKMd2uUtZizaYUJAPZ9KgmsNtIQIMqIiKtk+EFAeWd4/AvMCowJD46vlvdZv59fkbPHnEMaHr3wyRGEYG6cylAlWOeq3Iqrhc18hmO5mvECEloJ3T1DTYIulR6gsCbNqv93dyvE0grrR79gwBCJ2DHEOi0rKVwsZUeSuWquxkfTpzwlhB0jYmo9VWV4="
  secret_access_key:
    secure: "FCqLXwNHCcN1DQb74aDIO1TMq2QwAHoYBosDabnRhK9WYO4wQFGGr/4PAPANSxLBdF8mkB9S9GgbXoee1c9O+t24Gcjw5rJ2/4o7dBCocm33v1Kh8v6MnpOvEGisIYFat7ELpY5D28w4GHgkzQNvCrSj94UQ1ZG8XFm5CGCHOwLuTkbtidxgqApm7L0xNibO3G7AAk//5Q0Ji9zydpX/yJYcQV9M03okNAhdxnohi4a43nPFoaeYxEeikzMXfgZSbg6iPJ8rdTjbxNF6MzQaiyX41zK7ae1ACiGju1O8mUNFNUe8lKFxXQdwTrfPAtSUFsnZKLrFNJdsa8HMPv3tUB05uO0kklJU3hlh8j4o8vMsd6DDnrtdFBCKJZMVRSLDRwiVwMtJCIPbCm46+xDHImjF8ztxUbOf/gzLf73pgr6PzZcD1LYAZX1E5UtrEX2FI8umLVt2a5jbWRD4eaAVlGQ4UPy9u66UfTYmQmvg0l2u7ZgvxZU9lNWnlRD78B/6vMzHpTQXGOpheUySJGxbEwADFrAgLjO7BRs+IzteN2b6UZ+SL42LjXYu2GPp8Jylit4Q2cUW9ZvyY0me0nqCGE15ThKcNdNv/k4z4kZbXe4kKbRQKvTM9Tf0fRUB/Ttrg2igfXuKYCep/uw31ta3mgCVmnjMLsujapqckoKV9W8="
  bucket: "S3 Bucket"
  skip_cleanup: true


