language: java
jdk: oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: yanisakli-github
    token:
      secure: o/x9ecVzFX/sd8W29DH5PsoI6Ct8PjXVZL3rZJajUu+HspnrvRd/6YMnZfRBJLmU5pw6XxxgTrg1H8JXydCI8ChigOQ4uaNvp7nBxx/kfXZ0+p2pFUH2jpf0YXrF0fgidExU5g0VZh5bbqsuOVSawqRVl0sneFe8nmrIRfSPvfGNlgNCAzPJK3txgd2j6BvUvLoQnbs1KhpHayICckUAl5b1/N/AGKQJwnBU3sHoECllPQhUyNTWzkc4ppnhkbjMS7gxy/M3GWeXrzcLqh3iGeDmEYyTQ/sPAKRRiPwnBJrKRjkeGNzs4EbIpuMoWzJpIwG3G8mBwSRnB8YZemWhGw8p4ye1bTdj8lV/m+YjbwffyJq9gFdQXmXyJgXZfxYGy/y04oPRcDm6P5qw4DUe23pAKvfB2s8yx59lOdL0e0ymrG8t7ELPoLh79/dnBA2aNYd7plGpjR3t5ebsgRhGb9pWGPrlyh5YBnQP3dWLpKBGLc3K3YKOVKDR8wCyL652hPu7QzRQr5B/2EX/eFNCwBH01/QKJujjexh5iRy6k7glpNfdgGcyk+KTMR72qzPzNsszNOK44hnqlnflRF/Ea3/Xv2Y6vnePHcP8pAU/2DAUTbwYmPrJZJV2LyqLGZxM2XM3yE9STpSJyxPO5lQEtp2V5vyjJLyzunkaIXZ1AdI=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yanisakli_JEE
  -DskipTests
- sonar-scanner -Dsonar.projectKey=yanisakli_JEE -Dsonar.sources=. -Dsonar.java.binaries=.

deploy:
  provider: s3
  access_key_id:
    secure: Bq1tYF5jwuBRTOpzQHmO6ipZFEl3I68TNIFdejG0b1DjXU8KRa7mGvZWk9Phq7mH+LfOCb4YiDtM14erq9++wmMD4dMEc8eXScEpd06PNGQRTBakwtyJVoeVige0UriS0N0SpkTqZYBaDg3Rc0y2xAbeIxz5vKQXJoLnw69Vtr7m1vpySr3i975LcCgUUsoRIqw6PY/bSlVhWHoHyDu4knn2v7ibU3aYnnpKn7LtBiO5DYZ9e9ZEGrinLsapFJcKyi+6l+EN9ZlfqgvMukpctZbQse7r5gZrIbawnSYfo9FJX8v6CjI+6JVPGFxh+wsh1roSmiPV5LXYaBUKyqhDVfooRtDPT9Njdg+nwaWBxKoaThoTuZordINwMb8oUFGzQxttyu5gdGUicRUr+8bIko8KUSi5qxIJWv1vNirytO5jSmkhGLlZrXukiSwKZMV3RdmqHCwB5TYv5Acz3mRrXMEfdFegcDLkvBRSBFEyODHErOUtpMWUMnKsQZTbtddkKuSHphP7WyOjZ9ggxuwQ/3NL8taIGahE2UeJwpRkCZL26BmcLSREJFkSp1Eq6npOckLN2ZztH7bXYV+Vk5N3miAjd+CTJ3rMZ7JA710RS16ToA2EEKfRhJVI6FOvpSoIyBy/8NFeD2qpLaQpOIeohFfI2TiWquBoFTABuS77+Ag=
  secret_access_key:
    secure: T0+FGZT0Ld6zPBOnPgEcy5qSveQS794JWnvCFplwc9oeXYEGogAkA+2KsIjC80fYAKpjAwd1TgJpYKdO6GLTaaF9lJMHhKLingWOjDd2D4YY8Qqg/wXCmM3mXpWloEalINodgxNQMep70K4/iT7nwuBpXk63dXUowGs4zDHDwLBuqm6wb8vzQV5DEWKFKPwuBG+lcdFnMmsWLZACUxv6VwBV9QD/sdwdvuLPG6B6Xt1vbeK4GrdwkCzO64rmcj3LF+Z2PvAbqk/xi5CSVf7UMSfzBWIApHzBE1WgI4NYAOSIRT84h/TR/CQxCyedJOhxchJKIu05I8pxEQBsv+H7XP1kETKZFZG4xJUYPwTOIeoV8V+g2da7x3psNg8OyE05SjVimApXD46DAZVKlNkde5km8jbGKdZNlWiyBdfrzeg38D+vFKZBtDzQ6Owbkn0ojnn4EH5aSOPKf57vD93/xSaCj/kgdzIkgVvq1K1MJY9HkFrkBLNJMvh7dLm/0OJr8/TRJh96M+y/WaFKsDAokE2w0m6cdwC78S9xddQaBNFd/aIW0verWcR6dM1uzbr0WjfR1NuLFzTBDl2awrTo/mvqQPoaUkEpDXJ9eUBsqwiv14h2SbM2Dw6HhIjgxw288m7y9fhWHixLAjRSZPnU4/lX/BCh943i36YPZ32wMF4=
  bucket: "wekaesgi"
  skip_cleanup: true


