language: java
jdk: oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: yanisakli-github
    token:
      secure: "o/x9ecVzFX/sd8W29DH5PsoI6Ct8PjXVZL3rZJajUu+HspnrvRd/6YMnZfRBJLmU5pw6XxxgTrg1H8JXydCI8ChigOQ4uaNvp7nBxx/kfXZ0+p2pFUH2jpf0YXrF0fgidExU5g0VZh5bbqsuOVSawqRVl0sneFe8nmrIRfSPvfGNlgNCAzPJK3txgd2j6BvUvLoQnbs1KhpHayICckUAl5b1/N/AGKQJwnBU3sHoECllPQhUyNTWzkc4ppnhkbjMS7gxy/M3GWeXrzcLqh3iGeDmEYyTQ/sPAKRRiPwnBJrKRjkeGNzs4EbIpuMoWzJpIwG3G8mBwSRnB8YZemWhGw8p4ye1bTdj8lV/m+YjbwffyJq9gFdQXmXyJgXZfxYGy/y04oPRcDm6P5qw4DUe23pAKvfB2s8yx59lOdL0e0ymrG8t7ELPoLh79/dnBA2aNYd7plGpjR3t5ebsgRhGb9pWGPrlyh5YBnQP3dWLpKBGLc3K3YKOVKDR8wCyL652hPu7QzRQr5B/2EX/eFNCwBH01/QKJujjexh5iRy6k7glpNfdgGcyk+KTMR72qzPzNsszNOK44hnqlnflRF/Ea3/Xv2Y6vnePHcP8pAU/2DAUTbwYmPrJZJV2LyqLGZxM2XM3yE9STpSJyxPO5lQEtp2V5vyjJLyzunkaIXZ1AdI="

before_install:
-chmod a+x ./mvnw

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yanisakli_JEE -DskipTests
- sonar-scanner -Dsonar.projectKey=yanisakli_JEE -Dsonar.sources=. -Dsonar.java.binaries=.


deploy:
  provider: launchpad
  slug: "~yanisakli/JEE/+git/master"
  oauth_token:
    secure: "NK9KUKJ+0VnQDlgdzrJzSp0X7liGvGoaf5Ppx46b+5pGWtQAn58zITVrcvpFBJPfCg7430ucWetHkF+VKzQZpJ13aVH3BBnHD3PUfxMgxAX41u1H4eyobPFsZymObqLnStctgBWtitgVbtSKKnP2OHa228cDHq0zW2Og0IRzTFFXIsOGibGF8KFkr2gs5ozVPZyhXKenTeH+vudlD8TQPwEmxKcEKT8iboUEygZMyBxkBYCsT4Lc1hQBx7uViEOziNBL52TSUtz7qqjilgiWIWtIM+u2i5ATlr8lslmD/7iortSaj4nPn1bO9W9V3vXng7muhWRqS4MfafiuH2op72nGhgT14tLf0B5zq6jEdJ63OZ1AZfguehoCNj+hIh6TfzgfeoKpFMzNL6e71RcYDLaOviX2Z5Ply0aOY977Vjzm65q7+KhDwCOHb2e7BurF1dK2hpHxSoOCmNFvxuc24rnCi6P5GR8ZT/36L+znjtR3PmPewrZFG+5wSlfWCR+vgGsnYHQwovfX5Zk8cqDLuOVp3qiCKssDt7s1MbftXf6LRNJuLYioaGVlZ+Qk8SJJ+hzk9hlHWWfw/TtPjpQVfTCsxq+kG8O+XNAdjPNJPfAMotleZtEugx+eh4mrtAQc1V/zzhK8vhDVlyI28Xm7KdVLLv2BsO51p4JmpjqzSRI="
  oauth_token_secret:
    secure: "on1msI8Sb0FdZJzGEmorBkpBAjIE9Yh/3Eui4Tpt9WReDaatIbd9UByOjvD1J8W9hN93ZYnqv8+wqNfOK3OL8DFguHvlKKNO1MxGZ4KxUw8bQGjpN3HLvH/5//guwnDOLoSCrtMIvzEgul8RyDnOc+tY3R/24qc1PQreXz8BKyO25FxtFqqska9mN0j7GbHx0I9PuvH9YAngOhJYTUSmkPaQtampT3oUdMemH4la+nBQp5ijl0NH+krVSN7lhTXT+oG3hBtPe26ZHYAdXnuf5+1luIMKSQtw8xzdOcH7VfM8caifW4YCNzAXzfpQcDQZe/HhNGB5Vi2ZDlqjr1Lqo2GCClT8Oq90G0MpCyFwfS3ixIlpPqe8H86uXXAaWTbEp4BbE+44iKqdFrzOVjGkEI3CnEQv5mn6oa/BhZ8VWCUhNTl3ha78qO7neKsTZbUmC3J/0hJOkt7trnRM8669S7+X/kTCGDVi6FHSWkSndUUpzDjDn2j9P/+7FgbEC1B5ANrAO377LP4bd/rHsGH55mhaNYy87U+9XfsThRYR7D1FDY6RZt5I+ocJq0K4ZgqWb95OhBQWSjKEcgqTjFlcqAe/X7OGWNCuCg5B4ImOMMUiKd+B2bouPKBwO8EDdpxry1sMl/KWidWUHuTegjN/bqFCN2onJI1EiNiDXe+Caxg="
  on:
    branch: master