language: java
jdk: oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: yanisakli-github
    token:
      secure: "o/x9ecVzFX/sd8W29DH5PsoI6Ct8PjXVZL3rZJajUu+HspnrvRd/6YMnZfRBJLmU5pw6XxxgTrg1H8JXydCI8ChigOQ4uaNvp7nBxx/kfXZ0+p2pFUH2jpf0YXrF0fgidExU5g0VZh5bbqsuOVSawqRVl0sneFe8nmrIRfSPvfGNlgNCAzPJK3txgd2j6BvUvLoQnbs1KhpHayICckUAl5b1/N/AGKQJwnBU3sHoECllPQhUyNTWzkc4ppnhkbjMS7gxy/M3GWeXrzcLqh3iGeDmEYyTQ/sPAKRRiPwnBJrKRjkeGNzs4EbIpuMoWzJpIwG3G8mBwSRnB8YZemWhGw8p4ye1bTdj8lV/m+YjbwffyJq9gFdQXmXyJgXZfxYGy/y04oPRcDm6P5qw4DUe23pAKvfB2s8yx59lOdL0e0ymrG8t7ELPoLh79/dnBA2aNYd7plGpjR3t5ebsgRhGb9pWGPrlyh5YBnQP3dWLpKBGLc3K3YKOVKDR8wCyL652hPu7QzRQr5B/2EX/eFNCwBH01/QKJujjexh5iRy6k7glpNfdgGcyk+KTMR72qzPzNsszNOK44hnqlnflRF/Ea3/Xv2Y6vnePHcP8pAU/2DAUTbwYmPrJZJV2LyqLGZxM2XM3yE9STpSJyxPO5lQEtp2V5vyjJLyzunkaIXZ1AdI="

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yanisakli_JEE -DskipTests
- sonar-scanner
env:
  global:
    secure: lD/3WVykxPI21c0gnCdvHwgiBkJq7efzWj7gPSTtjjV/qC6RpJuP9YD/qCJKtyw0/Eil2DQXULFTYNHS3AMgoAAYHh+03Xwbo8XzMfTBjj6Bhfsmz6zwlnUfaob0k1AUHS5TJxItUAYDksU6PvvpyFjvjzHFnqnd3VThLGrWoFmVID4zWqhhY1ciPESMm1soL9d56uf6QJH0BKzhetf3YJkrNxZPsUZgls4dhwP9JWqAxYretLdJtvVv9BUYPA3BQjNcbSs8jIm4/F7GIWjoLqKPjSH1UrlBICnrsLoU8P+0q7UB7QMWTFYRkJksdWBe+Um4dQlrvx3VwqLRM4XHqxI5Ulsa6OV6kcPWoxFuGwXmDfkgWfY4zVbLOcUcFMrkcf3LrenHopodPfvG8Gl/cyjk7dPZbBO5wBjexi3PCSSO6m1N7alccCIRXSSd8MH0gRjaZtXFFZ+XzyVZrcrIM8tBdXR+HGrICPlzF2hdBgA3LDIpcTQWRd5jh9ojtHx6RrPuVaAUpVkT2jXfbVfRysNRLaQv+EPgOIvXmO5EBwqx2zfYRfflylLIbbjcqO13Gfj+VQKFdlpSNpsCtfR2k4PcThoArqEonsPQmJuOLDiDXeRPr13yDw86I+Ykdbh2uIGUvSrat+YlMJfx3DgzVEaNfH4O71GLL+gi4u9UxLI=
