language: java
jdk: oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: yanisakli-github
    token:
      secure: o/x9ecVzFX/sd8W29DH5PsoI6Ct8PjXVZL3rZJajUu+HspnrvRd/6YMnZfRBJLmU5pw6XxxgTrg1H8JXydCI8ChigOQ4uaNvp7nBxx/kfXZ0+p2pFUH2jpf0YXrF0fgidExU5g0VZh5bbqsuOVSawqRVl0sneFe8nmrIRfSPvfGNlgNCAzPJK3txgd2j6BvUvLoQnbs1KhpHayICckUAl5b1/N/AGKQJwnBU3sHoECllPQhUyNTWzkc4ppnhkbjMS7gxy/M3GWeXrzcLqh3iGeDmEYyTQ/sPAKRRiPwnBJrKRjkeGNzs4EbIpuMoWzJpIwG3G8mBwSRnB8YZemWhGw8p4ye1bTdj8lV/m+YjbwffyJq9gFdQXmXyJgXZfxYGy/y04oPRcDm6P5qw4DUe23pAKvfB2s8yx59lOdL0e0ymrG8t7ELPoLh79/dnBA2aNYd7plGpjR3t5ebsgRhGb9pWGPrlyh5YBnQP3dWLpKBGLc3K3YKOVKDR8wCyL652hPu7QzRQr5B/2EX/eFNCwBH01/QKJujjexh5iRy6k7glpNfdgGcyk+KTMR72qzPzNsszNOK44hnqlnflRF/Ea3/Xv2Y6vnePHcP8pAU/2DAUTbwYmPrJZJV2LyqLGZxM2XM3yE9STpSJyxPO5lQEtp2V5vyjJLyzunkaIXZ1AdI=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=yanisakli_JEE
  -DskipTests
- sonar-scanner -Dsonar.projectKey=yanisakli_JEE -Dsonar.sources=. -Dsonar.java.binaries=.

deploy:
  provider: gae
  keyfile:
    secure: R44nh2xwuL8amaNGSqjKdCAEIq9CVDvqJ4fgPFqCpuO3U98kZqtFyF6cnVxs4gZsHdXLnA7lspu8x30ZAjGgN4XJaXFH83Tqm9x7CBSYumzXFJIWrtWWrQbSTL1mPAkvnAT+XILLwACdA2cDJEw3TjGnJceZATN3R46M1XrBLqHDhFdjVC4LJLqqLuQ1blStNfHo9Aq6EEe2nXlBopUSqQuEUlAQIYYxjmgoiaUM0PgAw1uZN5ZG0GN6lo+2CamDgF0Fks7tb8rdseXC5OeoCTUYDQ6iwHGrcJ7DrX5cDairgXEbzQw6Qir4BaHk/gEwodCTjsYoZV3LDzH7Pk9OggtabeisQgv4cyTP+QXuNrfno22eP2ip35PpBT+z3hsh0XowyYx0pDUlUoOMwTsgncpgxZMnuLY6+8PLDlHdrbWtkA+9xyIpANdfGtRvJRhTMSBYIa0K2OPz+8miRdvjOim47WakiRk8SJB70ZcvafLccr1Zpa3AYfMdq4Fm+uhDFHaoeJW1B9i+hGy36UwX5YDToktEOWdsqrIfNypWNa5e9DumM8242wvXl3/hzHBS76EXLJFeKFhK5MY4Gn8o8dh87RRsNB5YNMI5ta2bCRLDUs4i7lbfB13ljhhcSzLQll04GO9TxxspepRd5qYsKfst5L1DRjt/vuxEKwv1AUI=
  project:
    secure: nKWzztZ/PIPqK04TpMU04LaeERVoxV+G7EfI8Uw7Dk2Ttw4OEBEGOl+s5v/WqwVBOHFXFW4VZ2tj+ZLQwa9zh1c7dNZFC12fJiKcqQN78y4kaBGGrfxrc+RG5BBqY1y8rAg6FMrchMhIhoWNBzeJFWJ0F+r8ilWHoqVJNfol8azSxH5IKSnCWEwqw2YzIQDc8xSTlVT9xrW/HwPwsaoW3JQyUa9cj0WuwI+/kv7L3EUpnYeIHdoi0KAYASLxGuDBapry8piPLz54A6LsSAerYmMki/R2ClIB7ZjJMqpBG1983i3RwxIUfMI5j9sf0fH7YVcdkyGlVAcaXG8ZgeGlDwEubd2+SdAwsuzRCnTha+HrrqiqCP4jIVo2BeFqhF4afI/fOXayFSEtSpBFahwBGlzdSKkE2s9FAIlNAapS6mw6A5+sY+LwtidgPsjAT7MOkl2gfPpkN9YYeJE2x4ZJPyAV3RcU0dKGVY0Ij0DwRKjUJbekUV8Kg20eLgtE5FOCZZkxiArGtT4xg08W90bOMfx6JslnvKg32161sgScuLL24BQfnZfAueCgyCkhzw7dyrw/r7aoIMpNNZch3CcazyiTXPSa1KT+W/qwb6Mu0nX2hjZz1EOoggATcLgnjDZycnjgp5dgm8exBtlYdfARkk8WyJn2fnKWtz6GgHwuILg=

